M48
; DRILL file KiCad 10.0.5 date 2026-09-07T18:36:45
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-09-07T18:36:45-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.5
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X5.0Y-5.0
X5.0Y-95.0
X12.1Y-44.1
X12.1Y-82.9
X80.9Y-44.1
X80.9Y-82.9
X145.0Y-5.0
X145.0Y-95.0
M30
